# Generated by Django 2.2.3 on 2019-07-16 13:31

import animais.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bovino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacao', models.CharField(max_length=255, unique=True, verbose_name='Brinco')),
                ('tipo', models.CharField(choices=[('Cria', 'Bovino de Cria'), ('Engorda', 'Bovino de Engorda')], default='Cria', max_length=10, verbose_name='Tipo')),
                ('peso', models.TextField(blank=True, null=True, verbose_name='Peso em Kg e sua Data')),
                ('medicamento', models.TextField(blank=True, null=True, verbose_name='Medicamento e sua Data de aplicação')),
                ('estado', models.CharField(choices=[('Possui', 'Possui'), ('Vendido', 'Vendido'), ('Morto', 'Morto')], default='Possui', max_length=10, verbose_name='Estado')),
                ('nascimento', models.DateField(help_text="<p class='comment'>Escreva no seguinte formato: <em>DD/MM/AAAA</em></p>", verbose_name='Data de Nascimento')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=1, verbose_name='Gênero')),
                ('foto_um', models.FileField(blank=True, null=True, upload_to=animais.models.Bovino.file_path, verbose_name='Foto Principal')),
                ('foto_dois', models.FileField(blank=True, null=True, upload_to=animais.models.Bovino.file_path, verbose_name='Segunda Foto')),
                ('foto_tres', models.FileField(blank=True, null=True, upload_to=animais.models.Bovino.file_path, verbose_name='Terceira Foto')),
                ('foto_quatro', models.FileField(blank=True, null=True, upload_to=animais.models.Bovino.file_path, verbose_name='Quarta Foto')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
            ],
        ),
        migrations.CreateModel(
            name='Filhos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('filhos', models.ManyToManyField(blank=True, help_text="<p class='comment'>Use CTRL para selecionar mais de um, ou deixar de selecionar um.</p>", null=True, to='animais.Bovino')),
            ],
        ),
        migrations.AddField(
            model_name='bovino',
            name='filho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='animais.Filhos'),
        ),
    ]
